const KOREA_DATA = {
  food: [
    { emoji:'🍚', name:'Bibimbap', kr:'비빔밥', desc:'Mixed rice bowl with veggies, egg & gochujang. Korea\'s most iconic dish.', tags:['rice','healthy','classic'], region:'Jeonju', mapQ:'Bibimbap restaurant Seoul' },
    { emoji:'🌶️', name:'Kimchi', kr:'김치', desc:'Fermented spicy cabbage served with every Korean meal. 2,000+ varieties!', tags:['fermented','spicy','side dish'], region:'Nationwide', mapQ:'Kimchi Museum Seoul' },
    { emoji:'🍖', name:'Korean BBQ', kr:'고기구이', desc:'Grill samgyeopsal or bulgogi at your table. Best with soju 🍶', tags:['BBQ','pork','beef'], region:'Nationwide', mapQ:'Korean BBQ restaurant Seoul' },
    { emoji:'🍢', name:'Tteokbokki', kr:'떡볶이', desc:'Spicy chewy rice cakes in gochujang — king of Korean street food.', tags:['street food','spicy'], region:'Street food', mapQ:'Tteokbokki Myeongdong Seoul' },
    { emoji:'🥩', name:'Bulgogi', kr:'불고기', desc:'Tender marinated beef with soy, pear & sesame. Grilled to perfection.', tags:['beef','marinated'], region:'Nationwide', mapQ:'Bulgogi restaurant Seoul' },
    { emoji:'🍜', name:'Jjajangmyeon', kr:'짜장면', desc:'Noodles in black bean sauce — Korea\'s favorite Chinese-Korean comfort food.', tags:['noodles','fusion'], region:'Incheon', mapQ:'Jjajangmyeon Incheon Chinatown' },
    { emoji:'🍲', name:'Kimchi Jjigae', kr:'김치찌개', desc:'Hearty kimchi stew with pork & tofu. Perfect winter comfort food.', tags:['stew','warm'], region:'Nationwide', mapQ:'Korean stew restaurant Seoul' },
    { emoji:'❄️', name:'Naengmyeon', kr:'냉면', desc:'Cold buckwheat noodles in icy broth. Refreshing summer specialty.', tags:['cold','noodles','summer'], region:'Nationwide', mapQ:'Naengmyeon restaurant Seoul' },
    { emoji:'🧇', name:'Pajeon', kr:'파전', desc:'Crispy savory pancake with green onions & seafood. Best with makgeolli!', tags:['pancake','seafood'], region:'Nationwide', mapQ:'Korean pancake restaurant Seoul' },
    { emoji:'🍡', name:'Japchae', kr:'잡채', desc:'Glass noodles stir-fried with colorful veggies & beef. Sweet & savory.', tags:['noodles','party food'], region:'Nationwide', mapQ:'Japchae restaurant Seoul' },
    { emoji:'🍧', name:'Bingsu', kr:'빙수', desc:'Shaved ice with sweet red beans, rice cakes & condensed milk. Summer icon!', tags:['dessert','summer'], region:'Nationwide', mapQ:'Bingsu dessert cafe Seoul' },
    { emoji:'🥟', name:'Mandu', kr:'만두', desc:'Korean dumplings — steamed, fried or in soup. Stuffed with pork or kimchi.', tags:['dumplings','street food'], region:'Nationwide', mapQ:'Mandu restaurant Insadong Seoul' },
    { emoji:'🍗', name:'Chimaek', kr:'치맥', desc:'Korean fried chicken + beer. The ultimate after-work combo!', tags:['chicken','beer','crispy'], region:'Nationwide', mapQ:'Korean fried chicken Hongdae Seoul' },
    { emoji:'🔥', name:'Dakgalbi', kr:'닭갈비', desc:'Spicy stir-fried chicken with rice cakes & veggies. Chuncheon\'s specialty!', tags:['chicken','spicy'], region:'Chuncheon', mapQ:'Dakgalbi Chuncheon Korea' },
    { emoji:'🦑', name:'Haemul Jeongol', kr:'해물전골', desc:'Spicy seafood hot pot loaded with shrimp, squid & clams. Incredible umami.', tags:['seafood','hot pot'], region:'Coastal cities', mapQ:'Korean seafood hotpot restaurant Busan' },
    { emoji:'🍵', name:'Makgeolli', kr:'막걸리', desc:'Cloudy rice wine — Korea\'s oldest alcoholic drink. Best chilled with pajeon!', tags:['drink','traditional','rice wine'], region:'Nationwide', mapQ:'Makgeolli bar Insadong Seoul' },
  ],
  travel: [
    { emoji:'🏯', name:'Seoul', kr:'서울', desc:'Capital city — Gyeongbokgung Palace, Namsan Tower, Bukchon Hanok Village, Myeongdong.', tags:['capital','palace','shopping'], region:'Seoul', mapQ:'Gyeongbokgung Palace Seoul' },
    { emoji:'🌊', name:'Busan', kr:'부산', desc:'Beach city with Haeundae, Gamcheon Culture Village & legendary seafood.', tags:['beach','seafood','culture'], region:'Busan', mapQ:'Haeundae Beach Busan' },
    { emoji:'🌋', name:'Jeju Island', kr:'제주도', desc:'UNESCO volcanic island — Hallasan, black lava beaches, haenyeo divers.', tags:['island','UNESCO','nature'], region:'Jeju', mapQ:'Jeju Island South Korea' },
    { emoji:'🏛️', name:'Gyeongju', kr:'경주', desc:'Ancient Silla capital — Bulguksa Temple, royal tombs, open-air museum.', tags:['ancient','UNESCO','temple'], region:'Gyeongju', mapQ:'Bulguksa Temple Gyeongju' },
    { emoji:'🏘️', name:'Jeonju Hanok Village', kr:'전주 한옥마을', desc:'700+ preserved traditional houses. UNESCO gastronomy city. Best bibimbap!', tags:['hanok','traditional','food'], region:'Jeonju', mapQ:'Jeonju Hanok Village' },
    { emoji:'⛰️', name:'Seoraksan', kr:'설악산', desc:'Dramatic granite peaks, waterfalls & Buddhist temples. Best in autumn!', tags:['mountain','hiking','autumn'], region:'Gangwon', mapQ:'Seoraksan National Park Korea' },
    { emoji:'🌉', name:'Incheon', kr:'인천', desc:'Gateway to Korea — Songdo smart city, Chinatown, world\'s best airport.', tags:['airport','smart city','chinatown'], region:'Incheon', mapQ:'Incheon Chinatown Korea' },
    { emoji:'🌲', name:'Nami Island', kr:'남이섬', desc:'Iconic tree-lined island from K-drama "Winter Sonata". Beautiful year-round.', tags:['K-drama','nature','romantic'], region:'Gapyeong', mapQ:'Nami Island Gapyeong Korea' },
    { emoji:'🔭', name:'DMZ Tour', kr:'비무장지대', desc:'The most heavily guarded border in the world. Unique historical day trip from Seoul.', tags:['history','unique','tour'], region:'Gyeonggi', mapQ:'DMZ tour from Seoul' },
    { emoji:'🏙️', name:'Hongdae', kr:'홍대', desc:'Youth hub — indie art, street performances, K-pop shops, clubs & cafes.', tags:['nightlife','K-pop','art'], region:'Seoul', mapQ:'Hongdae district Seoul' },
    { emoji:'🛕', name:'Andong Hahoe Village', kr:'안동 하회마을', desc:'UNESCO World Heritage village. Traditional mask dance festival each autumn.', tags:['UNESCO','traditional','festival'], region:'Andong', mapQ:'Andong Hahoe Folk Village' },
    { emoji:'🎪', name:'Yeosu', kr:'여수', desc:'Scenic coastal city with stunning night views, Odongdo Island & fresh seafood.', tags:['coastal','seafood','scenic'], region:'Yeosu', mapQ:'Yeosu Odongdo Island Korea' },
  ],
  transport: [
    { emoji:'🚄', name:'KTX Bullet Train', kr:'KTX 고속열차', desc:'Seoul→Busan in 2h 20min at 300km/h. Cleanest, most punctual option.', tags:['fast','efficient','comfortable'], region:'Nationwide', mapQ:'Seoul Station KTX' },
    { emoji:'🚇', name:'Seoul Metro', kr:'서울 지하철', desc:'23 lines, 700+ stations. Cleanest subway in the world. English everywhere.', tags:['subway','WiFi','clean'], region:'Seoul', mapQ:'Seoul subway station' },
    { emoji:'💳', name:'T-money Card', kr:'T-머니 카드', desc:'Rechargeable card for metro, bus, taxi. Buy at any CU/GS25. 10% cheaper!', tags:['card','essential','all transport'], region:'Nationwide', mapQ:'GS25 convenience store Seoul' },
    { emoji:'✈️', name:'Incheon Airport', kr:'인천국제공항', desc:'World\'s #1 airport — shopping, sleeping pods, ice rink, spa inside.', tags:['airport','world #1','transit'], region:'Incheon', mapQ:'Incheon International Airport' },
    { emoji:'🚌', name:'Express Bus', kr:'고속버스', desc:'Comfortable intercity buses to all Korean cities. Budget-friendly.', tags:['budget','intercity'], region:'Nationwide', mapQ:'Seoul Express Bus Terminal' },
    { emoji:'🚕', name:'Kakao T Taxi', kr:'카카오 택시', desc:'Korea\'s #1 ride-hailing app. English interface. Cheaper than Uber.', tags:['taxi','app','english'], region:'Nationwide', mapQ:'taxi Seoul Korea' },
    { emoji:'⛴️', name:'Ferry to Jeju', kr:'제주도 여객선', desc:'Overnight ferry from Mokpo/Busan to Jeju Island. Scenic & budget option.', tags:['island','overnight','Jeju'], region:'Southern coast', mapQ:'Mokpo Ferry Terminal Jeju' },
    { emoji:'🚲', name:'Ddareungi Bike', kr:'따릉이 자전거', desc:'Seoul\'s public bike share — 1 hour for ₩1,000. Great along Han River!', tags:['bike','budget','Han River'], region:'Seoul', mapQ:'Han River Park Seoul bicycle' },
    { emoji:'🛵', name:'Electric Scooter', kr:'전동킥보드', desc:'Kakao T Bike & Lime scooters in major cities. QR scan rental.', tags:['eco','last mile','city'], region:'Major cities', mapQ:'Hongdae Seoul scooter' },
    { emoji:'🛤️', name:'ITX Saemaul Train', kr:'ITX 새마을', desc:'Scenic slower intercity train. Perfect for smaller towns not on KTX.', tags:['scenic','budget','slow train'], region:'Nationwide', mapQ:'Seoul Station Korea train' },
  ],
  companies: [
    { emoji:'📱', name:'Samsung', kr:'삼성전자', desc:'World\'s #1 smartphone & chipmaker. Founded 1938. Revenue $234B+.', tags:['electronics','chips','global #1'], region:'Suwon HQ', mapQ:'Samsung Digital City Suwon' },
    { emoji:'🚗', name:'Hyundai', kr:'현대자동차', desc:'8th largest automaker worldwide. Expanding rapidly into EVs & robotics.', tags:['automotive','EV','global'], region:'Seoul', mapQ:'Hyundai Motor Studio Seoul' },
    { emoji:'📺', name:'LG Electronics', kr:'LG전자', desc:'World leader in OLED TVs & home appliances. Also in solar & EVs.', tags:['OLED','appliances','global'], region:'Seoul', mapQ:'LG Science Park Seoul' },
    { emoji:'🟡', name:'Kakao', kr:'카카오', desc:'Korea\'s super app — KakaoTalk used by 95% of Koreans. Fintech, mobility, entertainment.', tags:['super app','messaging','fintech'], region:'Jeju / Seoul', mapQ:'Kakao headquarters Jeju' },
    { emoji:'🔍', name:'Naver', kr:'네이버', desc:'Korea\'s #1 search engine. Owns LINE (Japan), Webtoon & AI platforms.', tags:['search','AI','internet'], region:'Seongnam', mapQ:'Naver headquarters Seongnam Korea' },
    { emoji:'🏗️', name:'SK Group', kr:'SK그룹', desc:'3rd largest conglomerate — SKT telecom, SK Hynix chips, EV batteries.', tags:['telecom','chips','batteries'], region:'Seoul', mapQ:'SK headquarters Seoul' },
    { emoji:'🏪', name:'Lotte', kr:'롯데', desc:'Retail giant — department stores, hotels, Lotte World (5th tallest tower in world).', tags:['retail','hotels','theme park'], region:'Seoul', mapQ:'Lotte World Tower Seoul' },
    { emoji:'✈️', name:'Korean Air', kr:'대한항공', desc:'Korea\'s flag carrier, one of Asia\'s largest airlines. Merged with Asiana 2024.', tags:['airline','flag carrier'], region:'Seoul', mapQ:'Korean Air headquarters Seoul' },
    { emoji:'🔋', name:'LG Energy Solution', kr:'LG에너지솔루션', desc:'World\'s #2 EV battery maker. Supplies Tesla, GM, Volkswagen globally.', tags:['batteries','EV','Tesla'], region:'Seoul', mapQ:'LG Energy Solution Korea' },
    { emoji:'🎮', name:'Krafton / NCSOFT', kr:'게임사', desc:'PUBG (Krafton), Lineage (NCSOFT). Korea is a global gaming powerhouse & esports hub.', tags:['gaming','PUBG','esports'], region:'Seoul', mapQ:'PC bang esports cafe Seoul' },
    { emoji:'🧪', name:'Samsung Biologics', kr:'삼성바이오로직스', desc:'Global biopharmaceutical contract manufacturer. One of the fastest-growing K-biotech firms.', tags:['biotech','pharma'], region:'Incheon', mapQ:'Samsung Biologics Incheon' },
    { emoji:'🏢', name:'POSCO', kr:'포스코', desc:'One of the world\'s largest steel producers. Expanding into lithium & battery materials.', tags:['steel','materials'], region:'Pohang', mapQ:'POSCO Pohang Korea' },
  ],
  kbeauty: [
    { emoji:'✨', name:'K-Beauty Skincare', kr:'K-뷰티 스킨케어', desc:'Korea\'s 10-step skincare routine — cleanse, tone, essence, serum, moisturize. World-leading in innovation.', tags:['skincare','routine','glow'], region:'Myeongdong', mapQ:'Myeongdong beauty shopping Seoul' },
    { emoji:'💄', name:'Innisfree', kr:'이니스프리', desc:'Korea\'s #1 natural beauty brand from Jeju Island. Affordable, eco-friendly skincare & cosmetics.', tags:['natural','Jeju','eco'], region:'Nationwide', mapQ:'Innisfree store Myeongdong Seoul' },
    { emoji:'🧴', name:'COSRX', kr:'코스알엑스', desc:'Global viral brand — Snail Mucin Essence and BHA Blackhead Power Liquid went worldwide on TikTok.', tags:['viral','TikTok','global'], region:'Online / Myeongdong', mapQ:'COSRX Korea beauty store' },
    { emoji:'🌸', name:'Sulwhasoo', kr:'설화수', desc:'Korea\'s luxury herbal skincare brand using ginseng & oriental herbs. Premium gifting option.', tags:['luxury','ginseng','premium'], region:'Nationwide', mapQ:'Sulwhasoo flagship store Seoul' },
    { emoji:'🧖', name:'Sheet Masks', kr:'마스크팩', desc:'Single-use sheet masks soaked in serum — Korea\'s most exported beauty product. ₩1,000 each!', tags:['affordable','serum','daily'], region:'All convenience stores', mapQ:'sheet mask Olive Young Seoul' },
    { emoji:'💅', name:'Olive Young', kr:'올리브영', desc:'Korea\'s #1 health & beauty store — thousands of K-beauty products. Must visit in Myeongdong!', tags:['store','variety','must-visit'], region:'Nationwide', mapQ:'Olive Young Myeongdong Seoul' },
    { emoji:'🏥', name:'Medical Tourism', kr:'의료관광', desc:'Korea is Asia\'s top plastic surgery & dermatology destination. Gangnam district has 500+ clinics.', tags:['surgery','dermatology','Gangnam'], region:'Gangnam Seoul', mapQ:'Gangnam plastic surgery clinic Seoul' },
    { emoji:'💋', name:'Lip Tints & BB Cream', kr:'립틴트 & BB크림', desc:'Korea invented BB cream and popularized gradient lip tints — now global beauty staples.', tags:['makeup','invention','global'], region:'Myeongdong', mapQ:'Korean makeup store Hongdae Seoul' },
  ],
  kpop: [
    { emoji:'🎤', name:'K-Pop Idol Culture', kr:'K팝 아이돌', desc:'BTS, BLACKPINK, EXO, NewJeans — K-pop dominates global charts. Meticulous training system.', tags:['music','global','fandom'], region:'Seoul', mapQ:'HYBE headquarters Seoul' },
    { emoji:'🏢', name:'HYBE / Big 4 Agencies', kr:'하이브 / 빅4 기획사', desc:'HYBE (BTS), SM (EXO, aespa), JYP (TWICE, Stray Kids), YG (BLACKPINK). Visit their HQs!', tags:['agency','BTS','BLACKPINK'], region:'Seoul', mapQ:'HYBE headquarters Yongsan Seoul' },
    { emoji:'🛍️', name:'K-Pop Merch Stores', kr:'K팝 굿즈 매장', desc:'Official shops & fan-run stores in Hongdae with albums, photobooks, lightsticks & seasons greetings.', tags:['merch','fan','albums'], region:'Hongdae Seoul', mapQ:'K-pop store Hongdae Seoul' },
    { emoji:'🎬', name:'K-Drama Tours', kr:'K드라마 투어', desc:'Visit filming locations from Crash Landing on You, Squid Game, Reply 1988 & more.', tags:['drama','filming','Netflix'], region:'Nationwide', mapQ:'Squid Game filming location Korea' },
    { emoji:'💃', name:'Gangnam Style & Dance', kr:'강남스타일 & 댄스', desc:'Gangnam District — the real Gangnam Style world. Luxury brands, clubs & plastic surgery clinics.', tags:['Gangnam','dance','luxury'], region:'Gangnam Seoul', mapQ:'Gangnam district Seoul Korea' },
    { emoji:'🎵', name:'Norebang (Karaoke)', kr:'노래방', desc:'Private karaoke rooms — quintessential Korean social experience. Open until 5am!', tags:['karaoke','nightlife','social'], region:'Nationwide', mapQ:'Norebang karaoke Hongdae Seoul' },
    { emoji:'🌟', name:'Lotte World K-Pop', kr:'롯데월드 K팝', desc:'Theme park with K-pop shows, concerts, and fan meetings. Indoor & outdoor sections.', tags:['theme park','concerts','fun'], region:'Seoul', mapQ:'Lotte World Seoul' },
    { emoji:'🎭', name:'Korean Webtoon & Anime', kr:'웹툰', desc:'Naver Webtoon is the world\'s #1 webcomic platform. Korean manhwa goes global via Netflix adaptations.', tags:['webtoon','manhwa','Netflix'], region:'Online', mapQ:'Korea Webtoon industry Seoul' },
  ],
  shopping: [
    { emoji:'🏬', name:'Myeongdong', kr:'명동', desc:'Seoul\'s #1 tourist shopping street — cosmetics, fashion, street food, duty-free stores.', tags:['cosmetics','fashion','tourist'], region:'Seoul', mapQ:'Myeongdong shopping street Seoul' },
    { emoji:'👗', name:'Dongdaemun Market', kr:'동대문 시장', desc:'24-hour fashion wholesale market — 30,000+ shops, designer to wholesale. Night market vibes!', tags:['fashion','24hr','wholesale'], region:'Seoul', mapQ:'Dongdaemun Design Plaza Seoul' },
    { emoji:'🧧', name:'Namdaemun Market', kr:'남대문 시장', desc:'Korea\'s oldest market (600 years!) — kitchenware, clothes, accessories, street food.', tags:['traditional','oldest','market'], region:'Seoul', mapQ:'Namdaemun Market Seoul' },
    { emoji:'🏪', name:'Lotte / Shinsegae Duty-Free', kr:'면세점', desc:'Massive duty-free stores at airports and downtown. Up to 30% off luxury brands.', tags:['duty-free','luxury','discount'], region:'Seoul / Incheon', mapQ:'Lotte Duty Free store Seoul' },
    { emoji:'📦', name:'Coupang', kr:'쿠팡', desc:'Korea\'s Amazon — next-day (even same-day) delivery. Order anything online!', tags:['online','delivery','tech'], region:'Online', mapQ:'Coupang headquarters Seoul' },
    { emoji:'🛒', name:'Costco Korea', kr:'코스트코', desc:'Famously loved in Korea — Korean Costco has unique local products & giant portions.', tags:['bulk','western','unique'], region:'Yangpyeong / Seoul', mapQ:'Costco Yangjae Seoul' },
    { emoji:'🎁', name:'Insadong Antiques', kr:'인사동 골동품', desc:'Traditional crafts, pottery, calligraphy & antiques. Best for authentic Korean souvenirs.', tags:['antiques','crafts','traditional'], region:'Insadong Seoul', mapQ:'Insadong traditional market Seoul' },
    { emoji:'🌙', name:'Night Markets', kr:'야시장', desc:'Banpo Hangang Park market, Yeouido Spring Festival market — food, crafts, live music under the sky.', tags:['night market','food','outdoor'], region:'Seoul', mapQ:'Banpo night market Seoul' },
  ],
  history: [
    { emoji:'👑', name:'Joseon Dynasty', kr:'조선왕조', desc:'500-year dynasty (1392–1897) — created Hangul alphabet, celadon ceramics, Confucian culture.', tags:['dynasty','Confucian','Hangul'], region:'Nationwide', mapQ:'Gyeongbokgung Palace Joseon Seoul' },
    { emoji:'⚔️', name:'Korean War & Independence', kr:'한국전쟁 & 독립', desc:'Liberation from Japan 1945, Korean War 1950–53. War Memorial in Yongsan is unmissable.', tags:['war','memorial','independence'], region:'Seoul', mapQ:'War Memorial of Korea Seoul' },
    { emoji:'🔵', name:'Silla Kingdom', kr:'신라왕국', desc:'Ancient kingdom (57BC–935AD) that unified Korea. Gyeongju is its treasure trove.', tags:['ancient','Gyeongju','gold'], region:'Gyeongju', mapQ:'Gyeongju National Museum Silla' },
    { emoji:'🏺', name:'Goryeo Celadon', kr:'고려청자', desc:'800-year-old celadon pottery — Korea\'s most exquisite craft. Collected worldwide.', tags:['ceramics','craft','museum'], region:'Gangjin', mapQ:'National Museum of Korea Seoul' },
    { emoji:'📜', name:'Hangul Day', kr:'한글날', desc:'Korean alphabet created in 1443 by King Sejong. Celebrated Oct 9th. One of world\'s most scientific scripts.', tags:['alphabet','language','Sejong'], region:'Nationwide', mapQ:'National Hangul Museum Seoul' },
    { emoji:'🌿', name:'Confucian Heritage', kr:'유교문화', desc:'600+ years of Confucian tradition shapes Korea — respect for elders, education, hierarchy.', tags:['Confucian','tradition','values'], region:'Nationwide', mapQ:'Dosan Seowon Confucian Academy Korea' },
    { emoji:'🎎', name:'Joseon Royal Tombs', kr:'조선왕릉', desc:'UNESCO World Heritage — 40 royal tombs around Seoul. Eerie, beautiful, perfectly preserved.', tags:['UNESCO','tombs','royal'], region:'Seoul suburbs', mapQ:'Joseon Royal Tombs Donggureung Korea' },
    { emoji:'🛡️', name:'Hwarang Warriors', kr:'화랑', desc:'Elite Silla warriors — ancient Korean knights. Inspired modern K-dramas & Korean martial arts.', tags:['warriors','drama','martial arts'], region:'Gyeongju', mapQ:'Gyeongju Silla history Korea' },
  ],
};

const CITIES = [
  { name:'Seoul',    kr:'서울',  color:'#e74c3c', lat:37.5665, lng:126.9780 },
  { name:'Busan',    kr:'부산',  color:'#3498db', lat:35.1796, lng:129.0756 },
  { name:'Incheon',  kr:'인천',  color:'#2ecc71', lat:37.4563, lng:126.7052 },
  { name:'Gyeongju', kr:'경주',  color:'#f39c12', lat:35.8562, lng:129.2247 },
  { name:'Jeonju',   kr:'전주',  color:'#9b59b6', lat:35.8242, lng:127.1480 },
  { name:'Jeju',     kr:'제주',  color:'#1abc9c', lat:33.4890, lng:126.4983 },
  { name:'Andong',   kr:'안동',  color:'#e67e22', lat:36.5684, lng:128.7294 },
  { name:'Yeosu',    kr:'여수',  color:'#00bcd4', lat:34.7604, lng:127.6622 },
];
