/* GENERATED by tools/gen-kpop-images.cjs — do not edit by hand.
   Artist photos from Wikidata P18 / Wikimedia Commons, as of 2026-08-08.
   Every entry carries author + licence; the UI MUST render that credit. */
window.KPOP_IMAGES = {
 "newjeans": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/260611_NewJeans.png/500px-260611_NewJeans.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Upload: dramatized",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:260611_NewJeans.png"
 },
 "blackpink": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Blackpink_Pink_Carpet_Event_4.jpg/500px-Blackpink_Pink_Carpet_Event_4.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "TV10 (티비텐)",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Blackpink_Pink_Carpet_Event_4.jpg"
 },
 "twice": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/260618_TWICE.png/500px-260618_TWICE.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Upload: K-POPit 티비텐",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:260618_TWICE.png"
 },
 "aespa": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Aespa_01.jpg/500px-Aespa_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "David Lee",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Aespa_01.jpg"
 },
 "ive": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Ive_at_the_2026_Golden_Disc_Awards.png/500px-Ive_at_the_2026_Golden_Disc_Awards.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "https://www.youtube.com/@_TV10",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ive_at_the_2026_Golden_Disc_Awards.png"
 },
 "lesserafim": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/%EB%A5%B4%EC%84%B8%EB%9D%BC%ED%95%8C%28LE_SSERAFIM%29_%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC_%EC%B6%9C%EA%B7%BC%EA%B8%B8%2C_%EB%B9%84%EC%A3%BC%EC%96%BC_%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4_LE_SSERAFIM_Music_Bank_%284K%29_03.png/500px-%EB%A5%B4%EC%84%B8%EB%9D%BC%ED%95%8C%28LE_SSERAFIM%29_%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC_%EC%B6%9C%EA%B7%BC%EA%B8%B8%2C_%EB%B9%84%EC%A3%BC%EC%96%BC_%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4_LE_SSERAFIM_Music_Bank_%284K%29_03.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "https://www.youtube.com/@_TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:%EB%A5%B4%EC%84%B8%EB%9D%BC%ED%95%8C(LE_SSERAFIM)_%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC_%EC%B6%9C%EA%B7%BC%EA%B8%B8,_%EB%B9%84%EC%A3%BC%EC%96%BC_%ED%8C%8C%EB%9D%BC%EB%8B%A4%EC%9D%B4%EC%8A%A4_LE_SSERAFIM_Music_Bank_(4K)_03.png"
 },
 "gidle": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/20241130_%28G%29I-dle_MMA_2024_Red_Carpet.jpg/500px-20241130_%28G%29I-dle_MMA_2024_Red_Carpet.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "K-POPIT 케이팝잇",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:20241130_(G)I-dle_MMA_2024_Red_Carpet.jpg"
 },
 "itzy": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Itzy_going_to_a_Music_Bank_recording_on_August_8%2C_2019.png/500px-Itzy_going_to_a_Music_Bank_recording_on_August_8%2C_2019.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Dispatch",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Itzy_going_to_a_Music_Bank_recording_on_August_8,_2019.png"
 },
 "redvelvet": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Red_Velvet_Music_Bank_Mini_Fan_Meeting_June_2024.jpg/500px-Red_Velvet_Music_Bank_Mini_Fan_Meeting_June_2024.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "티비텐",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Red_Velvet_Music_Bank_Mini_Fan_Meeting_June_2024.jpg"
 },
 "nmixx": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/NMIXX_in_Oakland.jpg/500px-NMIXX_in_Oakland.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "David Lee",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:NMIXX_in_Oakland.jpg"
 },
 "stayc": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/STAYC_in_Seattle.jpg/500px-STAYC_in_Seattle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "David Lee",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:STAYC_in_Seattle.jpg"
 },
 "babymonster": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/BABYMONSTER_in_Seattle.jpg/500px-BABYMONSTER_in_Seattle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "David Lee",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:BABYMONSTER_in_Seattle.jpg"
 },
 "illit": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/%EC%95%84%EC%9D%BC%EB%A6%BF_%28ILLIT%29_%EA%B0%80%EC%9A%94%EA%B4%91%EC%9E%A5_%EC%B6%9C%EA%B7%BC%EA%B8%B8_%281%29.jpg/500px-%EC%95%84%EC%9D%BC%EB%A6%BF_%28ILLIT%29_%EA%B0%80%EC%9A%94%EA%B4%91%EC%9E%A5_%EC%B6%9C%EA%B7%BC%EA%B8%B8_%281%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "티비텐",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:%EC%95%84%EC%9D%BC%EB%A6%BF_(ILLIT)_%EA%B0%80%EC%9A%94%EA%B4%91%EC%9E%A5_%EC%B6%9C%EA%B7%BC%EA%B8%B8_(1).jpg"
 },
 "kissoflife": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/KISS_OF_LIFE_at_Music_Bank_%284K%29_20240705_01.png/500px-KISS_OF_LIFE_at_Music_Bank_%284K%29_20240705_01.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "https://www.youtube.com/@_TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:KISS_OF_LIFE_at_Music_Bank_(4K)_20240705_01.png"
 },
 "bts": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg/500px-BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "The White House",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:BTS_during_a_White_House_press_conference_May_31,_2022_(cropped).jpg"
 },
 "seventeen": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/SEVENTEEN%28%EC%84%B8%EB%B8%90%ED%8B%B4%29_-_%27Ready_to_love%27_%EC%9D%91%EC%9B%90%EB%B2%95_3m_25s.jpg/500px-SEVENTEEN%28%EC%84%B8%EB%B8%90%ED%8B%B4%29_-_%27Ready_to_love%27_%EC%9D%91%EC%9B%90%EB%B2%95_3m_25s.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "SEVENTEEN",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:SEVENTEEN(%EC%84%B8%EB%B8%90%ED%8B%B4)_-_%27Ready_to_love%27_%EC%9D%91%EC%9B%90%EB%B2%95_3m_25s.jpg"
 },
 "straykids": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png/500px-Stray_Kids_at_the_40th_Golden_Disc_Awards%2C_January_10%2C_2026_%281%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "K-POPIT 케이팝잇",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Stray_Kids_at_the_40th_Golden_Disc_Awards,_January_10,_2026_(1).png"
 },
 "txt": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/TXT_at_Soribada_Awards_on_August_23%2C_2019.png/500px-TXT_at_Soribada_Awards_on_August_23%2C_2019.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Dispatch",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:TXT_at_Soribada_Awards_on_August_23,_2019.png"
 },
 "enhypen": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Enhypen_in_2026_at_GDA.png/500px-Enhypen_in_2026_at_GDA.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "https://www.youtube.com/@_TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Enhypen_in_2026_at_GDA.png"
 },
 "ateez": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/ATEEZ_in_August_2024_%28cropped%29.jpg/500px-ATEEZ_in_August_2024_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "pinkllamanade",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:ATEEZ_in_August_2024_(cropped).jpg"
 },
 "nct127": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/181012_NCT127_KBS_%27%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC%27_%EB%A6%AC%ED%97%88%EC%84%A4_%EC%B6%9C%EA%B7%BC%EA%B8%B8_%EC%A7%81%EC%BA%A0_%EC%98%81%EC%83%81_02.png/500px-181012_NCT127_KBS_%27%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC%27_%EB%A6%AC%ED%97%88%EC%84%A4_%EC%B6%9C%EA%B7%BC%EA%B8%B8_%EC%A7%81%EC%BA%A0_%EC%98%81%EC%83%81_02.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "뉴스인스타 (News In Star)",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:181012_NCT127_KBS_%27%EB%AE%A4%EC%A7%81%EB%B1%85%ED%81%AC%27_%EB%A6%AC%ED%97%88%EC%84%A4_%EC%B6%9C%EA%B7%BC%EA%B8%B8_%EC%A7%81%EC%BA%A0_%EC%98%81%EC%83%81_02.png"
 },
 "nctdream": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/180902_%EC%8A%A4%EC%B9%B4%EC%9D%B4%ED%8E%98%EC%8A%A4%ED%8B%B0%EB%B2%8C_NCT_DREAM_2.jpg/500px-180902_%EC%8A%A4%EC%B9%B4%EC%9D%B4%ED%8E%98%EC%8A%A4%ED%8B%B0%EB%B2%8C_NCT_DREAM_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Explicit",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:180902_%EC%8A%A4%EC%B9%B4%EC%9D%B4%ED%8E%98%EC%8A%A4%ED%8B%B0%EB%B2%8C_NCT_DREAM_2.jpg"
 },
 "treasure": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/230415_%ED%8A%B8%EB%A0%88%EC%A0%80_Hello_Tour_in_Manila.jpg/500px-230415_%ED%8A%B8%EB%A0%88%EC%A0%80_Hello_Tour_in_Manila.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "takatajeon",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:230415_%ED%8A%B8%EB%A0%88%EC%A0%80_Hello_Tour_in_Manila.jpg"
 },
 "zerobaseone": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Zerobaseone_at_Blue_Paradise_media_showcase_Feb_24_2025.png/500px-Zerobaseone_at_Blue_Paradise_media_showcase_Feb_24_2025.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "TV10 티비텐",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Zerobaseone_at_Blue_Paradise_media_showcase_Feb_24_2025.png"
 },
 "riize": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Riize_at_the_2024_Melon_Music_Awards-2.png/500px-Riize_at_the_2024_Melon_Music_Awards-2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "TenAsia",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Riize_at_the_2024_Melon_Music_Awards-2.png"
 },
 "theboyz": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/The_Boyz_at_the_Dream_Concert_event_on_May_18%2C_2019.jpg/500px-The_Boyz_at_the_Dream_Concert_event_on_May_18%2C_2019.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "THE BOYZ",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:The_Boyz_at_the_Dream_Concert_event_on_May_18,_2019.jpg"
 },
 "exo": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Exo_monster_160618_suwon.png/500px-Exo_monster_160618_suwon.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "https://www.youtube.com/user/mang2goon/about",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Exo_monster_160618_suwon.png"
 },
 "iu": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/250718_Lee_Ji-eun_%28%EC%9D%B4%EC%A7%80%EC%9D%80%29.png/500px-250718_Lee_Ji-eun_%28%EC%9D%B4%EC%A7%80%EC%9D%80%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "티비텐 TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:250718_Lee_Ji-eun_(%EC%9D%B4%EC%A7%80%EC%9D%80).png"
 },
 "jungkook": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Jung_Kook_of_BTS%2C_February_12%2C_2026_%281%29.png/500px-Jung_Kook_of_BTS%2C_February_12%2C_2026_%281%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "K-POPIT 케이팝잇",
  "license": "CC BY 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Jung_Kook_of_BTS,_February_12,_2026_(1).png"
 },
 "lisa": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/20240314_Lisa_Manoban_07.png/500px-20240314_Lisa_Manoban_07.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "K-POPIT 케이팝잇",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:20240314_Lisa_Manoban_07.png"
 },
 "jennie": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Jennie_2026_GDA_1.jpg/500px-Jennie_2026_GDA_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "티비텐 TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Jennie_2026_GDA_1.jpg"
 },
 "rose": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Blackpink_Ros%C3%A9_Rimowa_1.jpg/500px-Blackpink_Ros%C3%A9_Rimowa_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "TV10",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Blackpink_Ros%C3%A9_Rimowa_1.jpg"
 },
 "gdragon": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/G-Dragon_in_February_2025.png/500px-G-Dragon_in_February_2025.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "K-POPIT 케이팝잇",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:G-Dragon_in_February_2025.png"
 },
 "taeyeon": {
  "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/251019_TAEYEON_%40MADLY_MEDLEY_2025.jpg/500px-251019_TAEYEON_%40MADLY_MEDLEY_2025.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
  "artist": "Spes Sublimitas",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:251019_TAEYEON_@MADLY_MEDLEY_2025.jpg"
 }
};
